export PS1="\$? \w \$ "
#export PATH=/Users/XXX/homebrew/sbin:/Users/XXX/homebrew/bin:$PATH
export HOMEBREW_CACHE=~/Library/Caches/Homebrew

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi
